#! /bin/sh
### BEGIN INIT INFO
# Provides:          lighnetd
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the Lightnet daemon
### END INIT INFO
#		Based on skeleton script written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian 
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#		Modified for olsrd
#		by Holger Levsen <debian@layer-acht.org>
#		Modified for Lightnet

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DIR=/opt/lightnet/bin/
DAEMON=/opt/lightnet/bin/lightnetd
NAME=lightnetd
DESC=lightnetd

PID_FILE=/var/run/$NAME.pid

test -x $DAEMON || exit 0

case "$1" in
 debug)
	if [ "$(pidof $NAME)" != "" ] ; then 
		echo "$NAME already running, doing nothing."
		exit 0
	fi
	echo -n "Starting $DESC: "
	start-stop-daemon --start --chdir $DIR --quiet --exec $DAEMON --pidfile $PID_FILE
	# sleep til olsrd has been started
	while ! pidof $NAME > /dev/null ; do 
	  sleep 1
	done
	echo "$NAME."        
	echo $(pidof $NAME) > $PID_FILE
	;;
 start)
	if [ "$(pidof $NAME)" != "" ] ; then 
		echo "$NAME already running, doing nothing."
		exit 0
	fi
	echo -n "Starting $DESC: "
	start-stop-daemon --start --chdir $DIR --background --quiet --exec $DAEMON --pidfile $PID_FILE
	# sleep til olsrd has been started
	while ! pidof $NAME > /dev/null ; do 
	  sleep 1
	done
	echo "$NAME."        
	echo $(pidof $NAME) > $PID_FILE
	;;
  stop)
	pidof $NAME || exit 0
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --signal TERM --quiet --exec $DAEMON --pidfile $PID_FILE
        rm -f $PID_FILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	$0 stop
	sleep 1
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
